### ISSUE TITLE
왠지모르지만 한사용자의 개근이 깨졌습니다.

### ISSUE THREAD

**Issue by hjhj3686** [qw5414/attendance#29]
![default](https://cloud.githubusercontent.com/assets/1341628/7902352/405b7cde-07f2-11e5-9eb8-d9db5304f19f.PNG)

이 버그가... 뭘까요.. 이사람 개근일이 깨졋는데..

**Comment by qw5414** [comment]
간혹 서버 시간과 연동에 문제있는것 같아요.
정확히 서버에서 표준시간과 몇초정도 차이나기 시작한다면.. 문제될수도 있거든요... 원인은 좀 더 분석해봐야겟지만요..;ㅁ;

**Comment by hjhj3686** [comment]
Db에서 연속출석일을 지정해줘서 해결했긴 했습니다 수동으로라도 지정이 가능해서 다행입니다..

**Comment by qw5414** [comment]
(_ _ ) 좋은 하루 되시기 바랍니다.
디비 연동 수정 옵션을 다음에 추가하도록 하겠습니다.

**Comment by qw5414** [comment]
`DB 연동 추가를 위한 이슈처리`
