### ISSUE TITLE
개근 출석 일수가 맞게 표시되지 않음

### ISSUE THREAD

**Issue by waldotic** [qw5414/attendance#31]
주간/월간/연간 개근은 알맞게 체크 하나, 리스트 상에서 개근 출석일이 알맞게 표시되지 않습니다.

**Comment by qw5414** [comment]
#29 그래서 개근일수를 정확하게 표현할 수 있도록 수정했었습니다. 참고해보세요..

**Comment by waldotic** [comment]
죄송합니다.. 그 이슈를 읽고 V7.0 으로 업그레이드 하였는데 어디서 수정해야 하는지 파악이 안되서요 ㅠㅠ

**Comment by qw5414** [comment]
개근 출석일수에 보통 마우스 올리면 됩니다..

**Comment by waldotic** [comment]
https://github.com/qw5414/att_bootstrap 이 스킨을 사용 중인데요.
view 목록에서 출석일수에 마우스 올려도 반응이 없습니다.
![2015-07-01 16 23 01](https://cloud.githubusercontent.com/assets/11609616/8449557/6d58b5e8-200d-11e5-99a0-ed4cbea3a309.PNG)

**Comment by qw5414** [comment]
기본 스킨 사용하시기 바랍니다. 해당 스킨과 다른 부분이 없습니다.

**Comment by waldotic** [comment]
감사합니다. 기본 스킨에서는 말씀하신 기능이 잘 동작합니다.
상단의 테이블 border 가 굵게 나오는건 제가 simplestrap 레이아웃을 사용해서 일까요?
![2015-07-01 16 25 10](https://cloud.githubusercontent.com/assets/11609616/8449586/c2c15b52-200d-11e5-9211-a79fd819b83f.PNG)

**Comment by qw5414** [comment]
@waldotic 네 아무래도..심플스트렙이 기본적인 출석부의 호환성을 망가뜨린느 부트스트랩 기본 설정이 강제화되어있는 부분이 있거든요..;ㅁ;

**Comment by waldotic** [comment]
@qw5414 스..슬픈 소식이군요 ㅠㅠ 아무튼 좋은 모듈에 신속한 답변 감사드립니다..!

**Comment by qw5414** [comment]
@waldotic 좋은하루 되십시오.
