### ISSUE TITLE
SSL 사용시 공지 흰화면

### ISSUE THREAD

**Issue by hjhj3686** [qw5414/attendance#33]
관리자 페이지 까지 SSL을 사용해서 일어난 일인듯합니다.

![default](https://cloud.githubusercontent.com/assets/1341628/8501953/7c29b228-21e5-11e5-90b7-4c908c248a33.PNG)

**Comment by qw5414** [comment]
거긴..뭐 뜨나 안뜨나 상관없습니다.. 제가 빈페이지로 해두면 아무것도 뜨지 않도록 되어있어서요../제사이트연결되는 부분입니다./
