### ISSUE TITLE
스탬프 출석기능

### ISSUE THREAD

**Issue by kaijess** [qw5414/attendance#38]
개요
- 출석체크에 쓸말도 없어서 그냥 ㅊㅊ, ㅎㅇ 등의 의미없는 출석메세지만 남겨짐
- 간편하게 출석체크를 하고 숨어있는 보너스 포인트 획득까지!
- 순위에 연연하지 않고 단순히 출석체크

구성
- 기존 출석부에 옵션을 두어 달력/스탬프를 선택하게 함
- 스탬프형식은 달력모양에 스탬프이미지가 비활성화 된 상태로 해당 이미지를 클릭하면 활성화되어 출석체크

**Comment by qw5414** [comment]
해당 부분은 스킨으로 구현이 가능하실 것 같습니다. (Document 사용하지 않고, 일반 출석부의 디비를 사용하게 하고나서 내용을 강제적으로 value 값을 강제적으로 주고, 오늘 날자의 구간에 해당 클릭이미지를 form  으로 잘 클릭유도할 수 잇는 방안으로 하시면 되실것 같습니다.
